spring:
  application:
    name: inventory-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/inventoryservice}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      enabled: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: inventory-service
  tracing:
    enabled: true
    sampling:
      probability: 1.0

loki:
  url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push

server:
  port: 8083
springdoc:
  pathsToMatch: /, /api/**
