services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=orderservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  orderservice:
    build:
      context: ./orderservice
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: P4ssword!