spring:
  application:
    name: api-gateway
  docker:
    compose:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm

server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Order Service
      url: aggregate/order-service/v3/api-docs
    urls[1]:
      name: Product Service
      url: aggregate/product-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /v3/api-docs

management:
  health:
   circuitbreakers:
     enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    enabled: true
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
            seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

loki:
  url: http://localhost:3100/loki/api/v1/push