spring:
  application:
    name: api-gateway
  docker:
    compose:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm
server:
  port: 9000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Order Service
      url: aggregate/order-service/v3/api-docs
    urls[1]:
      name: Product Service
      url: aggregate/product-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /v3/api-docs