apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: order-service
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=

