spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: P4ssword!
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        type:
          preferred_uuid_jdbc_type: CHAR
  docker:
    compose:
      file: orderservice/docker-compose.yml
